### ISSUE TITLE
Make LinearMap objects callable

### ISSUE THREAD

**Issue by dkarrasch** [Jutho/LinearMaps.jl#106]
As suggested by @Jutho in #102, one could make `LinearMap` objects callable via
```julia
(L::LinearMap)(x::AbstractVector) = L*x
```
But this seems to fail in Julia v1.0, so I'll leave this here as an issue in case someone knows how to make it work there, or when we drop v1.0 support.

**Comment by dkarrasch** [comment]
Today, I went through the Julia versions starting from v1.0.5. Adding methods to abstract types seems to be possible starting from v1.3. I think I'll add that and make a compat annotation saying that this is not available in older versions.

**Comment by Jutho** [comment]
Thanks for the careful maintainance!
