### ISSUE TITLE
Stable docs doesn't exist

### ISSUE THREAD

**Issue by Wikunia** [Jutho/LinearMaps.jl#109]
Unfortunately there are no stable docs for your package. 
It seems like you added the ssh key for Documenter only recently. If you want to have stable docs a new version needs to be registered or you can build the docs locally and push to the `gh-pages` branch.

**Comment by dkarrasch** [comment]
Thanks, @Wikunia, we are currently working towards the first stable version that includes Documenter documentation, but haven't finished yet. That includes some new parts of the documentation.
