### ISSUE TITLE
Function maps with additional arguments.

### ISSUE THREAD

**Issue by MKAbdElrahman** [Jutho/LinearMaps.jl#138]
I want to use  a bloch boundary condition,  the phase is another input to the function. Does LinearMap(f,..) expects f to have only the input vector x and output y ?
Can I do something like this ? 

function mrightdiff!(y::AbstractVector, x::AbstractVector, phase) # minus right difference
    N = length(x)
    length(y) == N || throw(DimensionMismatch())
      y[N] =  x[N] - phase * y[1]
    @inbounds for i=1:N-1
        y[i] = x[i] - x[mod1(i+1, N)]
    end
    return y

Thanks
end

**Comment by Jutho** [comment]
> I want to use a bloch boundary condition, the phase is another input to the function. Does LinearMap(f,..) expects f to have only the input vector x and output y ?

Yes, you can always make a nameless closure if you want to use this function as a linear map with a specific phase:
```julia
phase = ...
L = LinearMap((y,x)->mrightdiff!(y, x, phase), ...)
```

**Comment by MKAbdElrahman** [comment]
Thank you so much!
