### ISSUE TITLE
Function mapping with tuple arguments

### ISSUE THREAD

**Issue by bsaul** [Jutho/LinearMaps.jl#140]
Is it possible to apply a `FunctionMap` type using function that takes tuple arguments?

For example, let's say I wanted to take a function that works (e.g.):

```julia
x = 5.0  
f₁ = μ -> x .- μ
r₁ = LinearMap(f₁, 1, 1) * [0.0]
@show r₁
```

and add an argument:

```julia
f₂ = ((μ, σ), ) -> x .- μ
r₂ = LinearMap(f₂, 1, 1) * [(0.0, 0.0)]
@show r₂
```

This results in a bounds error:

```
ERROR: LoadError: BoundsError: attempt to access 1-element Array{Tuple{Float64,Float64},1} at index [2]
```

I'm a total beginner with Julia, so any help is appreciated. 

Thanks,
-Bradley

**Comment by bsaul** [comment]
I see. I think I'm being silly and conflating  "function" with functionmap.

You're right that `f₂` isn't linear. In fact, in general, I want to work with linear maps of (potentially) non-linear functions. For example, I might what to do something like:   

![image](https://user-images.githubusercontent.com/4882990/110492118-e5f3c880-80bf-11eb-81b9-234e8d462a6e.png)

But like a `FunctionMap`, I want `f*x` to mean `f(x)`.

**Comment by dkarrasch** [comment]
> conflating "function" with functionmap.

Perhaps. `FunctionMap` in this package means a linear(!) map that is given by the action of a function... instead of a matrix. What do you need the "pseudolinear" structure (I mean your $f$-$g$-$h$matrix) for?

**Comment by bsaul** [comment]
> What do you need the "pseudolinear" structure (I mean your $f$-$g$-$h$matrix) for?

That was just a contrived example, but in general I was toying around with defining, composing, and applying general linear maps of functions. 

Here's a more specific example. I have something like below. 

```julia
make_ψᵢ = x::Number -> ((μ, σ²), ) -> [ (x - μ); ((x - μ)^2 - σ²) ]
z = rand(1000)
l = map(make_ψᵢ, z) 
ψ( (μ, σ²) ) = reduce(+, map(f -> f((μ, σ²)), l))
```

The details of what `make_ψᵢ` returns isn't super important other than returning a vector of some sort. Here, it's the estimating equations for the mean and variance. Also, in practice, the input to  `make_ψᵢ`, `x`, might be more complicated than a scalar number. In principle, it could be a linear map (matrix). 

The goal I had in mind when I started the thread was to create a function like `ψ` via `LinearMaps`, which here I've used a `map/reduce` pattern to get to. I realize not all map/reduce operations map (pun intended) into a linear structure. But I *think* my example does up to the application of each `ψᵢ`.

**Comment by dkarrasch** [comment]
I don't think `LinearMaps.jl` is what you're looking for. You may find useful, however, the fact that functions are objects in Julia. Take this example for inspiration:
```julia
julia> using Statistics

julia> funs = (mean, var) # this is a tuple, but you could put them also in a vector [mean, var]
(Statistics.mean, Statistics.var)

julia> x = rand(10);

julia> map(f -> f(x), funs)
(0.45227814185283155, 0.09434872724573001)

julia> mapreduce(f -> f(x), +, funs)
0.5466268690985616
```
I'd recommend https://discourse.julialang.org/ for such discussions.

**Comment by bsaul** [comment]
Cool. Thanks for your help.
