### ISSUE TITLE
Conversion of a LinearMap to Dense or Sparse Matrix

### ISSUE THREAD

**Issue by MKAbdElrahman** [Jutho/LinearMaps.jl#144]
In many cases for testing the performance of a `LinearMaps` compared to sparse or dense arrays, I need a method to convert `LinearMap` to a dense or a sparse array. May be adding conversion functions to `LinearMaps.jl` will be useful.
  
Here is a preliminary implementation 
First, I define unit vector 
```julia
struct ê <: AbstractVector{Int}
    n::Int
    k::Int
end

Base.size(e::ê) = (e.n,)
Base.getindex(e::ê,i::Int)  = Int(e.k == i)

```
The collect method is used to covert lazy representations to dense ones
```julia
function Base.collect(lmap::LinearMap{T})  where T
    m,n = size(lmap);
    A = Array{T}(undef,m,n)
    for j in 1:n #fill by column
        A[:,j] = lmap * ê(m,j)
    end
    return A
end
```

The sparse method is used in `SparseArrays` to convert dense to sparse arrays

```julia
function SparseArrays.sparse(lmap::LinearMap{T})  where T
    m,n = size(lmap);
    A =   spzeros(m,n);
    for j in 1:n #fill by column
        A[:,j] = sparse(lmap * ê(m,j))
    end
    return A
end

```
Edit: This could be useful for LinearMaps defined from function maps. For wrapped linearmaps collect and sparse should just remove the external wrapper.

**Comment by dkarrasch** [comment]
We do have such functions already. You can simply call `Matrix(A)` or `sparse(A)`. For the latter, you need to declare `using SparseArrays` before. Check out our wonderful documentation! 😉

**Comment by MKAbdElrahman** [comment]
Yes,  Julia has just reported that I'm overwriting  the `sparse` method. looking at `conversion.jl` I found more than I need :)

Thank you
