### ISSUE TITLE
Positive definiteness of `CompositeMap`s

### ISSUE THREAD

**Issue by dkarrasch** [Jutho/LinearMaps.jl#148]
I think our current `isposdef` check of `CompositeMap`s is not (completely) correct. For instance, for a product like `A' * B * A` we say effectively say it's positive definite if `B` is. But for `A` with rank deficiency, that is not correct. So I wonder how breaking it would be to err in the opposite direction, remove any logic and have the default `false` for posdef'ness of `CompositeMap`s and let users manually set that field?

**Comment by dkarrasch** [comment]
Closing in favor of #149.

**Comment by JeffFessler** [comment]
Oops, sorry I missed this issue!
I definitely prefer having only the least expensive logic and defaulting to false.
I actually didn't realize that the user could manually set fields for composite maps, but I just looked in the (helpful!) docs and learned that one can wrap a LM and thereby set the field(s).  Good to know :)

**Comment by dkarrasch** [comment]
Exactly, and that's the mechanism we use in pretty much every promotion of matrices to `LinearMaps` internally. We never used to change the defaults, which are calls to `issymmetric`/`ishermitian`/`isposdef`, which again you only see when looking carefully at the `WrappedMap` constructor.
