### ISSUE TITLE
Clash between hvcat in LinearAlgebra/src/uniformscaling.jl and LinearMaps/src/blockmap.jl

### ISSUE THREAD

**Issue by andreasvarga** [Jutho/LinearMaps.jl#158]
I finished the transition of linear operators defined in the [MatrixEquations.jl](https://github.com/andreasvarga/MatrixEquations.jl) package from LinearOperators- to LinearMaps-based implementation and uploaded the new version of the package. The tests run well on the current Julia version (I assume 1.6.2), but lead to errors on the Nighly version. A typical error is generated by the line

`S = schur([A  -G; -Q  -copy(A')])`

in a Riccati equation solver. Here `G` and `Q` are UniformScalings and A is a square matrix. The error message is:

```
Continuous Riccati equation (Float64, n = 30, m = 10): Error During Test at /home/runner/work/MatrixEquations.jl/MatrixEquations.jl/test/test_riccati.jl:52
  Got exception outside of a @test
  MethodError: hvcat(::Tuple{Int64, Int64}, ::Matrix{Float64}, ::Matrix{Float64}, ::LinearAlgebra.UniformScaling{Float64}, ::Matrix{Float64}) is ambiguous. Candidates:
    hvcat(rows::Tuple{Vararg{Int64}}, A::Union{Number, LinearAlgebra.UniformScaling, AbstractVecOrMat}...) in LinearAlgebra at /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.8/LinearAlgebra/src/uniformscaling.jl:428
    hvcat(rows::Tuple{Vararg{Int64}}, As::Union{LinearAlgebra.UniformScaling, LinearMaps.LinearMap, AbstractVecOrMat}...) in LinearMaps at /home/runner/.julia/packages/LinearMaps/r6i00/src/blockmap.jl:172
  Possible fix, define
    hvcat(::Tuple{Vararg{Int64}}, ::Vararg{Union{LinearAlgebra.UniformScaling, AbstractVecOrMat}})
```

I encountered similar issues with the LinearOperator package (from which I transited to LM) and the authors managed somehow to restrain the promotion of their hvcat.  I wonder if this is also possible with LM. I also wonder what is the cause of the changed behaviour from version 1.6.2 to the nightly version.

**Comment by dkarrasch** [comment]
I've submitted a PR to Julia to fix the problem.

**Comment by dkarrasch** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/41511.
