### ISSUE TITLE
No warning for invalid sizes in FunctionMaps

### ISSUE THREAD

**Issue by JeffFessler** [Jutho/LinearMaps.jl#160]
A student of mine was debugging code and discovered that `FunctionMaps` do not report inconsistencies between the declared map size and the output of the function:

```julia
using LinearMaps
up = 2
x = zeros(2, 3)
m, n = size(x)
A = LinearMap(x -> zeros(eltype(x), up .* size(x)), up^2*m*n, m*n) # subtle bug here in output size
y = A * vec(x) # no error or warning!
```

Maybe this is a feature? 😄 

It could be addressed by adding a check after this line (and in similar places):

https://github.com/Jutho/LinearMaps.jl/blob/744800af0f07033f61112ad4213ac4ba7116bfaa/src/functionmap.jl#L67

like
```
size(y) == size(A,1) || throw(DimensionMismatch())
```

I guess the question is whether the "overhead" that all users would incur for the size check is worth it for saving some debugging time by other users.  Personally I'd be in favor of adding the check, and am willing to make the PR.  After all, we already check the input size:

https://github.com/Jutho/LinearMaps.jl/blob/744800af0f07033f61112ad4213ac4ba7116bfaa/src/functionmap.jl#L52

so it seems natural to check the output too.  The "pro" users who care about efficiency are more likely to use the mutating versions `mul!` that appropriately seem to lack size checks if I am reading `_unsafe_mul!` correctly.

Thoughts?

**Comment by dkarrasch** [comment]
In `mul!` the size checks are done once in `mul!` and then never again inside the `_unsafe_mul!` machinery. I think a size check as you propose would be ok (and necessary), because other parts of the code rely on `size` being correct. Think of the sum of different maps, which are checked for consistent size at construction.
