### ISSUE TITLE
SVD of a LinearMap?

### ISSUE THREAD

**Issue by dkarrasch** [Jutho/LinearMaps.jl#20]
I tried to compute the singular value decomposition of a LinearMap, for which I have functions for itself and its transpose, and failed. For instance, with the example given on the main page:
```
using LinearMaps

function leftdiff!(y::AbstractVector, x::AbstractVector) # left difference assuming periodic boundary conditions
    N=length(x)
    length(y)==N || throw(DimensionMismatch())
        @inbounds for i=1:N
    y[i]=x[i]-x[mod1(i-1,N)]
    end
    return y
end

function mrightdiff!(y::AbstractVector, x::AbstractVector) # minus right difference
    N=length(x)
    length(y)==N || throw(DimensionMismatch())
    @inbounds for i=1:N
        y[i]=x[i]-x[mod1(i+1,N)]
    end
    return y
end

D=LinearMap(leftdiff!, mrightdiff!, 100; ismutating=true)
svd(D)
```
I obtain
```
ERROR: MethodError: no method matching svd(::LinearMaps.FunctionMap{Float64,#leftdiff!,#mrightdiff!})
Closest candidates are:
  svd(::BitArray{2}) at linalg/bitarray.jl:101
  svd(::Base.LinAlg.AbstractTriangular) at linalg/triangular.jl:2204
  svd(::Diagonal{#s268} where #s268<:Number) at linalg/diagonal.jl:362
  ...
Stacktrace:
 [1] macro expansion at /Users/karrasch/.julia/v0.6/Atom/src/repl.jl:118 [inlined]
 [2] anonymous at ./<missing>:?
```
With `svds(D)` I obtain
```
ERROR: MethodError: Cannot `convert` an object of type LinearMaps.FunctionMap{Float64,#leftdiff!,#mrightdiff!} to an object of type Base.LinAlg.SVDOperator
This may have arisen from a call to the constructor Base.LinAlg.SVDOperator(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] #_svds#125(::Int64, ::Bool, ::Float64, ::Int64, ::Int64, ::Array{Float64,1}, ::Array{Float64,1}, ::Function, ::LinearMaps.FunctionMap{Float64,#leftdiff!,#mrightdiff!}) at./linalg/arnoldi.jl:406
 [2] #svds#124(::Array{Any,1}, ::Function, ::LinearMaps.FunctionMap{Float64,#leftdiff!,#mrightdiff!}) at ./linalg/arnoldi.jl:382
 [3] svds(::LinearMaps.FunctionMap{Float64,#leftdiff!,#mrightdiff!}) at ./linalg/arnoldi.jl:382
 [4] macro expansion at /Users/karrasch/.julia/v0.6/Atom/src/repl.jl:118 [inlined]
 [5] anonymous at ./<missing>:?
```
I understand that I can get the SVD information from `eigs(D'*D;nev=3,which=:SR)` and `eigs(D*D';nev=3,which=:SR)`, but I was curious if it was possible to do that directly, particularly so since the `svds` docs state regarding the input 

> `A`: Linear operator whose singular values are desired. `A` may be represented as a subtype of `AbstractArray`, e.g., a sparse matrix, or any other type supporting the four methods `size(A)`, `eltype(A)`, `A * vector`, and `A' * vector.

All of which are provided by a LinearMap. In any case, I think it would be helpful to briefly comment on the SVD case on the main page, which is otherwise very clear.

**Comment by dkarrasch** [comment]
Thanks for the quick reply. Please file an issue. You'll certainly explain more clearly and may have a suggestion how to correct. Many thanks! I'll close this one then?

**Comment by dkarrasch** [comment]
Thanks, @Jutho, for taking care of my issue. As of today, unfortunately not even `eigs` is working with `LinearMap`s on Julia 0.7_alpha, where the implementation is in `IterativeEigensolvers.jl` or `Arpack.jl`, I'm a bit confused.

**Comment by Jutho** [comment]
Is the problem with LinearMaps? It will probably need to be updated for julia 0.7, which I surely won't have time for this week. Anybody that wants to take a stab at it, I would very much welcome a PR.

**Comment by dkarrasch** [comment]
I don't think so. Calling
```
using LinearAlgebra, LinearMaps
eigs(LinearMap(rand(20,20)))
```
leaving unspecified where to take `eigs` from, results in
```
ERROR: MethodError: no method matching mul!(::SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true}, ::LinearMaps.WrappedMap{Float64,Array{Float64,2}}, ::SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true})
```
Hm, I just `Pkg.test`ed `LinearMaps` on Julia 0.7. Besides some deprecations, it has an issue with `UndefVarError: A_mul_B! not defined`. I can try to take a closer look, but I'm not very familiar with package development, even more so with the new package manager.

Regarding the current issue, the latest updates on Julia 0.6's `LinAlg` may not yet have been transferred to `Arpack.jl`.

**Comment by Jutho** [comment]
This is likely due to the major restructuring of `LinAlg`, now `LinearAlgebra` in Julia Base. Various methods have been renamed or restructured (e.g. the multiplication methods, transposition, ...).

Nothing unsurmountable, but it won't be a simple process of running Femtocleaner in order to make `LinearMaps` ready for julia 0.7. I will try to invest some time as soon as possible (hopefully next week).

**Comment by dkarrasch** [comment]
Now tracked in [JuliaLinearAlgebra/Arpack.jl#13](https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/13). Additionally, we should add some examples on how to connect to `IterativeSolvers` at some point.
