### ISSUE TITLE
Specialized algebra for matrix-induced LinearMap's

### ISSUE THREAD

**Issue by dkarrasch** [Jutho/LinearMaps.jl#21]
I had an idea regarding matrix-induced LinearMap's and was wondering if it is any good. Does it make sense to distinguish the case when you work exclusively with `LinearMap`s which are generated from (sparse) matrices, and to define, say, `A+B` as `WrappedMap(A+B)`? This requires additional computation time at construction, but after a single application to a vector this is already balanced compared to having a `LinearCombination(A,B)` (notation is pseudo-ish, of course). Similar with scalar multiplication and subtraction. If one had such a distinction, one could, in fact, define `Inverse(A)` by replacing the usual multiplication with `\`. Also, inversion commutes with transposition/taking the adjoint, and behaves completely analogously to those for composed linear maps. It seems that it should fit nicely.

Certainly, one can code that for some special use case into a function and generate a `FunctionMap`, but this may be generic enough to be considered for the package?

**Comment by dkarrasch** [comment]
I did some more testing and realized that the idea is no good. The only benefit would have been the "inverse" type whose multiplication was `\` instead of `*` or function evaluation. On the (significant) downside, adding two matrices (even more so sparse ones with distinct `nzvals` distribution) does take a lot more time than matrix-vector multiplication, and the "inverse multiplication" can be easily done via a `FunctionMap`.

**Comment by Jutho** [comment]
My apologies for the late response. I myself do not use sparse matrices often, but I would indeed have assumed that `(A+B)*v` could be more costly than `A*v + B*v`. Thanks for testing.

**Comment by dkarrasch** [comment]
Well, it's a nontrivial balancing issue. Testing `(A+B)`(even without the matrix-vector-product) versus `A*v + B*v` may not hit the right point. Addition of two matrices or scalar multiplication is a one-time action only. In contrast, the matrix-vector-product may be computed many many times in an `eigs`-computation. In that case, each `A*v + B*v` is at least twice as expensive as `(A+B)*v`, after `A+B` has been computed.

I just tested with `(1000, 1000)` dense matrices: after seven matrix-vector-multiplications, the initial effort of adding `A` and `B` already pays off (economists call that the break-even point 😄). That's not too bad, actually. With the "Inverse" convenience in mind, it may still be worth introducing a sub-type of `WrappedMap`, say `MatrixMap` or so? Within that type, all operations would act directly on the `lmap`-field, obviously except for the multiplication. Along the lines of `TransposeMap`, one could then have an `InverseMap` or `InverseMatrixMap`, whose multiplication is defined by `\`. One would need to think about an in-place version of it, à la `A_mul_B!`.

I could give it a try unless you think this would pollute your package and if you're willing to include it at some point. And one would need to think about how the user can choose at construction if (s)he wants a `WrappedMap` or a `MatrixMap`, because users may wish to have one or the other feature (no costs at construction at the potentially additional expense when computing (many) matrix-vector-products vs. additional costs at construction with cheaper multiplication).

**Comment by Jutho** [comment]
Sure, I am open to such a PR. But is there a good use case, where you have two matrices and you really want `LinearMap(A)+LinearMap(B)` to add the matrices, without being able to just do `LinearMap(A+B)` yourself?

**Comment by dkarrasch** [comment]
As I'm thinking about it, you may be right. We don't need a new type and all that. Effectively, what I wanted, i.e., `inv(LinearMap(A::AbstractArray))` can be implemented by
```
# A = rand(100,100)
rmul! = (u,v) -> A_ldiv_B!(u,A,v)
lmul! = (u,v) -> At_ldiv_B!(u,A,v)
LinearMap(A,rmul!,lmul!,size(A)...)
```
It takes two more lines, and I wonder in which scope `A` is and if access will be fast, but surely it doesn't require introducing a new type and rewriting all the operations for it. Thanks for your consideration!
