### ISSUE TITLE
Add lmul! and rmul!

### ISSUE THREAD

**Issue by dkarrasch** [Jutho/LinearMaps.jl#25]
The Arpack.jl update is through. To be able to use `Arpack.svds(L)` for a `LinearMap`, we will certainly need an `rmul!(::LinearMap,::Diagonal)` instance. I'd implement this by
```
function LinearAlgebra.rmul!(A::LinearMap, D::Diagonal)
    size(D, 1) == size(A, 2) || throw(DimensionMismatch("rmul!"))
    A = A * D
end
```
Since the result of `A * D` is a `LinearMap`, which is cheap to construct, I don't see any issue with the fact that this is not mutating as it is supposed to be in the `Array`/`Vector` setting with memory allocation etc.

Generally, this raises the issue whether we should add instances of `rmul!(::LinearMap,::Number)` and the same for `lmul!` in addition to the `::Diagonal` case. The latter would simply return a `LinearCombination`.

**Comment by dkarrasch** [comment]
Hm, I overlooked that the output is going to be correct, but `A` is not going to be replaced by the output but keeps having the original value... Even worse, in `Arpack.jl` we would actually need a matrix representation of `A * D`. That cannot be done "inplace" by any means. Seems like we'll have to resort to the svd function provided by IterativeSolvers.jl, see the discussion in [Arpack#13](https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/13).

**Comment by dkarrasch** [comment]
Just to wrap up: With the latest `Arpack.jl` update, there is no need to define `rmul!` and alike, and `Arpack.svds(::LinearMap)` should just work.

**Comment by Jutho** [comment]
That's great, I indeed don't think adding an `rmul!` method which ends up not updating the linear map in place (which is impossible since they are immutable structs) is a good idea, and it seems like there is something fundamentally wrong with the implementation of `svds` if that would be needed.
