### ISSUE TITLE
Convert coefficients in linear combinations to promote_type?

### ISSUE THREAD

**Issue by dkarrasch** [Jutho/LinearMaps.jl#33]
I am working on a minor improvement in our handling of linear combinations, i.e., avoiding allocation of `z = similar(y)` when the length of `A.maps` is 1. Such linear combinations occur when we multiply a linear map with a scalar factor, for instance. This is how I realized that we don't convert the coefficients to the `promote_type`, take e.g.
```
function Base.:(*)(α::Number, A::LinearMap)
    T = promote_type(eltype(α), eltype(A))
    return LinearCombination{T}(tuple(A), tuple(α))
end
```
Or rather, we leave it to the `lmul!` in `A*_mul_B!` to do this, well, at every multiplication, which may be many times in an iterative algorithm. As a quick benchmark, consider
```
using BenchmarkTools, LinearAlgebra
@btime lmul!($(rand()),$(rand(Complex{Float64}, 5000))) #  199.095 μs (0 allocations: 0 bytes)
@btime lmul!($(rand(Complex{Float64})),$(rand(Complex{Float64}, 5000))) # 188.849 μs (0 allocations: 0 bytes)
```
Confusingly, the opposite effect occurs here:
```
α = 2
@btime lmul!($(convert(Int64, α)), $(rand(5000))) #  523.188 ns (0 allocations: 0 bytes)
@btime lmul!($(convert(Float64, α)), $(rand(5000))) # 868.077 ns (0 allocations: 0 bytes)
```
Admittedly, it is exactly `lmul!` that seems to be affected by recent changes in `LinearAlgebra`, so this may need testing on nightly? I'm on standard
```
julia> versioninfo()
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = atom -a
  JULIA_NUM_THREADS = 4
```
Any opinions?

**Comment by Jutho** [comment]
Not sure, it might actually be that the second one dispatches to BLAS, whereas the mixed case, which is faster, is just handled by generic Julia code, which by now turns out to be faster.

**Comment by dkarrasch** [comment]
Interestingly, @andreasnoack seems to have kicked out the BLAS dependency in `r/lmul!` recently. On Julia master, I find only one method definition:

https://github.com/JuliaLang/julia/blob/534fe442d41fb55749a12444ae6f38970c2dfb59/stdlib/LinearAlgebra/src/generic.jl#L75-L80

(as opposed to more specialized one, that took into account that the `eltype(A)` and the `typeof(s)` coincided, and was deleted a few days ago). That means we need to look at some combinations of scalar types (timings are on Julia v1.0.1, not on master, but these basic operations haven't change, I guess):
```
julia> @btime 2 * 3.0;
  1.420 ns (0 allocations: 0 bytes)

julia> @btime 2.0 * 3.0;
  0.031 ns (0 allocations: 0 bytes)

julia> @btime 2 * (3.0 + 1.0im);
  1.421 ns (0 allocations: 0 bytes)

julia> @btime 2.0 * (3.0 + 1.0im);
  1.421 ns (0 allocations: 0 bytes)

julia> @btime (2.0 + 0.0im) * (3.0 + 1.0im);
  1.421 ns (0 allocations: 0 bytes)
```
Think of the `2` as the coefficient, while the right factors correspond to the vector components. So, it doesn't seem to be a bad idea to have the coefficients already converted at construction. On the other hand, my considerations may be biased by thinking of the type `T` of `LinearMap`s as a subtype of `Number`, which we never require.

CC-ing @andreasnoack for recommendations.

**Comment by Jutho** [comment]
> That means we need to look at some combinations of scalar types

I am not sure why you would look at scalar multiplication. We never multiply the vector components directly, we always use a primitive such as `lmul!`, `rmul!` or `axpy!`, which, as you measured above, are fast. I think these methods do the conversion before the loop (or maybe not, but the conversion is probably hoisted out of the loop automatically by LLVM).

**Comment by dkarrasch** [comment]
I see. I wasn't sure (or better, had no idea) what the compiler would do, I just saw the `s * X[I]` in the code. Also, I saw that doing `lmul!` of a complex number with a complex vector is faster than doing it with a real number and a complex vector. That's why I felt there might be room for improvement.

**Comment by Jutho** [comment]
> doing lmul! of a complex number with a complex vector is faster than doing it with a real number and a complex vector

If the difference is significant, you should definitely open an issue about such things on the Julia github page.
