### ISSUE TITLE
LinearMaps on IterativeSolvers.jl

### ISSUE THREAD

**Issue by lopezm94** [Jutho/LinearMaps.jl#4]
In IterativeSolvers.jl we are currently doing our own simplified version of LinearMaps, the reason is there is a concern about the maintenance of this package. I would be glad to help on "rekindling" this package whenever I can since it would be better to have this kind of things outside of IterativeSolvers.jl. Anything you need help with?

**Comment by Jutho** [comment]
Strangely enough I don't recall ever getting an email notification about this issue, so I just stumble across it today. I guess the maintenance of this package is not super active, but it is certainly not abandoned.  Some fixes will be necessary for 0.5 I assume; I can try to make some time in the next few weeks. I am not currently using it myself, hence indeed the low activity.

**Comment by lopezm94** [comment]
Great!, I could help with documentation or anything you need. Github qualifying me as a bot was probably the cause you didn't get notified.

**Comment by Jutho** [comment]
I think this can be closed? With the recent updates, LinearMaps.jl is fully compatible with current julia and I think in a more or less polished state (hence my tagging v1.0.0). As stated in https://github.com/JuliaMath/IterativeSolvers.jl/issues/34 , I would actually not mind transferring ownership and maintenance of this package to the JuliaMath community.
