### ISSUE TITLE
hcat of LinearMaps

### ISSUE THREAD

**Issue by JeffFessler** [Jutho/LinearMaps.jl#45]
`hcat` for ordinary matrices works as expected of course
```
a = ones(3,2)
b = zeros(3,4)
@show c = [a b]
```
but `hcat` for two LinearMaps produces a 1x2 array of LinearMaps:

```
A = LinearMap(x -> a*x, y -> a'*y, 3, 2)
B = LinearMap(x -> b*x, y -> b'*y, 3, 4)
# C = [A B] # returns a 1x2 Array of LinearMaps.FunctionMap
```

It is easy to overload `hcat` so that LinearMaps behave like matrices:

```
using Base: hcat
function Base.hcat(A::LinearMap, B::LinearMap) # overload hcat for LinearMap
    c1 = size(A,2)
    c2 = size(B,2)
    @assert size(A,1) == size(B,1)
    return LinearMap(x -> hcat(A*x[1:c1], B*x[(c1+1):(c1+c2)]),
        y -> vcat(A'*y, B'*y), size(A,1), c1 + c2)
end
```

However, the LinearMap returned by this simple overloading does not work with the operation `Matrix()`
```
C = [A B] # returns a new LinearMap
@show size(C)
@show C * ones(6) # works as expected
@show C' * ones(3) # also works
@show Matrix(C') # works
@show Matrix(C) # Fails!?
```

It returns this error:

> BoundsError: attempt to access 3-element view(::Array{Float64,2}, :, 1) with eltype Float64 at index [1, 2, 3, 4, 5, 6]

Is this a bug in `Matrix()` or is there some bug in my (very simple) over-loading of `hcat`?
(I have used similar overloading in my Matlab equivalent of `LinearMaps` for years.)

Personally I would recommend that `hcat` and `vcat` overloading be a regular part of LinearMaps and I can provide the code if you are amenable to that, but if not then it would be helpful for me at least if you could identify why my overloading is failing.

Thanks.

**Comment by dkarrasch** [comment]
There is a bug in your definition. It should be `+` instead of `hcat` in the function map.
```
function Base.hcat(A::LinearMap, B::LinearMap) # overload hcat for LinearMap
    c1 = size(A,2)
    c2 = size(B,2)
    @assert size(A,1) == size(B,1)
    return LinearMap(x -> A*x[1:c1] + B*x[(c1+1):(c1+c2)], size(A,1), c1 + c2)
end
```
I have a couple of comments.

1. For generic `LinearMaps` code, you should not assume that adjoints are defined. I think it's a bit suboptimal to define a `.fc` function, since the package will then think that the adjoint is defined, when it may not.
2. If I understand `?@assert` correctly, then it is not recommended for use cases as yours here. Rather, one would use something like `size(A,1) != size(B,1) && throw(DimensionMismatch())`.
3. For a generic implementation, I see an explosion of possibilities to take care of. Let's say `A` and `B` have an in-place multiplication
```
A = LinearMap((y,x) -> mul!(y, a, x), (y,x) -> mul!(y, a', x), 3, 2)
B = LinearMap((y,x) -> mul!(y, b, x), (y,x) -> mul!(y, b', x), 3, 4)
```
Then you may wish to consider to use the in-placeness somehow (one would need to test if that pays off)
```
function Base.hcat(A::LinearMap, B::LinearMap) # overload hcat for LinearMap
    c1 = size(A,2)
    c2 = size(B,2)
    @assert size(A,1) == size(B,1)
    return LinearMap((y, x) -> (mul!(y, A, @view x[1:c1]); y .+= B*view(x, (c1+1):(c1+c2))), size(A,1), c1 + c2)
end
```
Also, as I wrote it, one would probably (regardless of other issues/properties) use views on the vectors, to avoid allocation of the subvectors.

I think we could include `hcat` functionality, but I think we should really take care of all the possible cases (adjoint, inplace) and deliver carefully optimized functionality.

**Comment by JeffFessler** [comment]
Daniel, thanks so much for pointing out my embarrassing bug and for the other notes.
Here is corrected code with `@view` that also handles the `fc` issue you mention.
This version is more general because it can handle `[A I]` and `[A B I]` etc. where `I` is the identity map that is often arises in such concatenations.
I do not know how to handle the general case `[I I I I ... I A]` though, but that's ok for now.
I don't have experience with in-place operations (matlab doesn't support it...) so I am just posting the code here in case it is a useful starting point for anyone who wants to generalize it to handle in-place operations.  I might look at it more over the summer.  `cat` and `vcat` are also of interest.

```
using LinearMaps
using LinearAlgebra: I
using Base: hcat

function hcat_lm(As...) # helper routine for hcat of LinearMaps
	nrow = 0
	for i=1:length(As) # find first non-I to specify number of rows
		if As[i] != I
			nrow = size(As[i],1)
			break
		end
	end
	nrow == 0 && throw(DimensionMismatch("need one non-I")) # [I I] illegal

	for i=1:length(As) # check row consistency
		if As[i] != I
			ndims(As[i]) != 2 && throw(DimensionMismatch("need ndims=2"))
			size(As[i],1) != nrow && 
				throw(DimensionMismatch("need same # of rows, " *
					"got (nrow = $nrow, $i => $(size(As[i],1)))"))
		end
	end
	ncol = map(A -> A == I ? nrow : size(A, 2), As)
	ncol = [0; ncol...] # trick for ranger()

	ranger = i -> (1+sum(ncol[1:i])) : sum(ncol[1:(i+1)]) # ith input range
	f = x -> sum([As[i] * (@view x[ranger(i)]) for i=1:length(As)])
	fc = y -> vcat(map(A -> A'*y, As)...)

	lacks_fc = A -> isa(A, LinearMap) && A.fc == nothing
	if any(map(A -> lacks_fc(A), As)) # any LinearMap missing adjoint?
		fc = ()
	else
		fc = (y -> vcat(map(A -> A'*y, As)...), )
	end
	return LinearMap(f, fc..., nrow, sum(ncol))
end


# overload hcat for LinearMap
Base.hcat(A::LinearMap, B::LinearMap) = hcat_lm(A, B)

# [A I] [A I I] [A I B C] etc.
Base.hcat(A::LinearMap, Bs...) = hcat_lm(A, Bs...)


function hcat_lm_test()
	a = ones(3,2)
	b = zeros(3,4)
	A = LinearMap(x -> a*x, y -> a'*y, 3, 2)
	B = LinearMap(x -> b*x, y -> b'*y, 3, 4)
	C = [A B I] # returns a new LinearMap :)
	@show size(C)
	@show C * ones(size(C,2))
	@show C' * ones(size(C,1))
	@show Matrix(C)' == Matrix(C')
end

hcat_lm_test()
```

**Comment by JeffFessler** [comment]
In case anybody finds it useful later, I have added these extensions (and others, with tests) to
https://github.com/JeffFessler/MIRT.jl
See the source code in
https://github.com/JeffFessler/MIRT.jl/tree/master/src/system
I'll likely make other extensions later.

**Comment by chriscoey** [comment]
It would be very handy to have hcat, vcat, and hvcat, at least for abstract matrices (but ideally also for other linear maps too). I am trying to solve systems where the LHS is a block matrix of dense and sparse and structured and zero matrices (from the KKT conditions for structured optimization problems).

**Comment by Jutho** [comment]
I agree that this would be useful; probably it's best to implement new special purpose types for this. Not sure when I will have time though, but any contribution is welcome.

**Comment by dkarrasch** [comment]
I think I've got something working, will post soon for testing and review.
