### ISSUE TITLE
Trouble using eigs() on a linear map, in Julia v0.5.0

### ISSUE THREAD

**Issue by sivark** [Jutho/LinearMaps.jl#5]
I'm using `Julia v0.5.0 (Commit 3c9d753)` and LinearMaps on `commit 912740d` (HEAD of this repository as of now). The following block of code 
```julia
using LinearMaps
function dummyfunc(op::Vector{Float64}) 
    return op
end
LinOp = LinearMap(dummyfunc, 6^6,issymmetric=false);
D,U=eigs(LinOp,nev=1)
```
fails with the error
> LoadError: MethodError: no method matching myfunc(::SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true})
Closest candidates are:
  myfunc(!Matched::Array{Float64,1})

The same code works fine on `Julia v0.4.7` (using `issym` instead of `issymmetric`)

Am I missing something? Thanks.

**Comment by Jutho** [comment]
Probably this is due to a change in `eigs`, which now acts on a subarray instead of on a simple `Vector`. You should write your dummyfunc to accept an `AbstractVector{Float64}`.
