### ISSUE TITLE
MethodList[end] error in Julia 0.5

### ISSUE THREAD

**Issue by raminammour** [Jutho/LinearMaps.jl#6]
Hello,

I had an error coming from `LinearMaps`, I tracked it down to the lines that have:
```julia
LoadError: MethodError: no method matching endof(::Base.MethodList)
```

The culprits are lines that have:
```julia

methods(Base.At_mul_B,(AbstractLinearMap,AbstractVector))[end]
``` 
The fix is easy:
```julia

methods(Base.At_mul_B,(AbstractLinearMap,AbstractVector)).ms[end]
``` 

Cheers!

**Comment by Jutho** [comment]
Thanks for reporting, I'll try to fix soon, though I was recently wondering about the usefulness of these definitions. All of the `AbstractLinearMap` types that I define do overwrite both the non-mutating and mutating versions of `At/c_mul_B(!)`.

**Comment by Jutho** [comment]
I think this is now fixed with a slightly different approach.
