### ISSUE TITLE
Matrix-free iterative method examples?

### ISSUE THREAD

**Issue by henry2004y** [Jutho/LinearMaps.jl#81]
Hi,

I found this package from Chris Rackauckas's PDE tutorial. I noticed from his presentation that the matrix-free form of iterative solvers can be easily implemented with LinearMaps, but it's still not clear to me how to do it.

In the manual of [IterativeSolvers](https://github.com/JuliaMath/IterativeSolvers.jl/blob/master/docs/src/getting_started.md), there's only descriptions but no examples.

The following simple example works on Julia 1.3:
```
# Matrix-free for Poisson equation with second order central difference
# https://github.com/ChrisRackauckas/JuliaCon2018PDEWorkshop/blob/master/PDEWorkshop.ipynb
using LinearAlgebra, IterativeSolvers
n = 10
A = rand(n, n)
A = A + A' + 2*n*I
b = rand(n)

struct SizedStrangMatrix
   size::Tuple{Int,Int}
end

Base.eltype(A::SizedStrangMatrix) = Float64
Base.size(A::SizedStrangMatrix) = A.size
Base.size(A::SizedStrangMatrix,i::Int) = A.size[i]

A = SizedStrangMatrix((length(b),length(b)))

import LinearAlgebra.mul!

function mul!(C,A::SizedStrangMatrix,B)
   for i in 2:length(B)-1
      C[i] = B[i-1] - 2B[i] + B[i+1]
   end
   C[1] = -2B[1] + B[2]
   C[end] = B[end-1] - 2B[end]
   C
end
Base.:*(A::SizedStrangMatrix,B::AbstractVector) = (C = similar(B); mul!(C,A,B))

U = gmres(A,b)
norm(A*U - b)
```

What should I do to make use of LinearMaps instead?

BTW, more intuitive examples in the Readme.md or documents would make life easier for newcomers like me~

**Comment by dkarrasch** [comment]
Hi @henry2004y, I'm very glad to hear that Chris is helping to spread the word, and that newcomers are discovering `LinearMaps.jl`. I agree we should have a more comprehensive "How to define a `LinearMap`" at some point. I believe, however, that after reading the whole README and the example, your use case should have been within reach. Maybe you could help us telling what you feel was missing in the README? The following code does the job.
```julia
function strangmul!(C, B)
    C[1] = -2B[1] + B[2]
    for i in 2:length(B)-1
        C[i] = B[i-1] - 2B[i] + B[i+1]
    end
    C[end] = B[end-1] - 2B[end]
    return C
end
using LinearMaps
A = LinearMap(strangmul!, 10; issymmetric=true, ismutating=true)
b = rand(10)

using IterativeSolvers, LinearAlgebra
U = gmres(A, b)
norm(A*U - b)
```
Note that `eltype`, `size` and size checking are already taken care of by the package.

**Comment by henry2004y** [comment]
Thank you for your response! 
My suggestion for the README file is to present ideas and simple tutorials before any updated new feature announcements. Someone like me may be only interested in the part we are using, so simple examples like this instead of saying this is feasible looks much more friendly.
Right now there seems to be only one example in README.md. We can add more and reorganize the file.

**Comment by Jutho** [comment]
Or, using the `do` block syntax from Julia
```julia
A = LinearMap(10; issymmetric=true, ismutating=true) do (C,B)
    C[1] = -2B[1] + B[2]
    for i in 2:length(B)-1
        C[i] = B[i-1] - 2B[i] + B[i+1]
    end
    C[end] = B[end-1] - 2B[end]
    return C
end
```

**Comment by dkarrasch** [comment]
> Or, using the `do` block syntax from Julia
> 
> ```julia
> A = LinearMap(10; issymmetric=true, ismutating=true) do (C,B)
>     C[1] = -2B[1] + B[2]
>     for i in 2:length(B)-1
>         C[i] = B[i-1] - 2B[i] + B[i+1]
>     end
>     C[end] = B[end-1] - 2B[end]
>     return C
> end
> ```

Hm, for some reason that doesn't seem to work :-(
```julia
julia> A * rand(10)
ERROR: MethodError: no method matching (::var"#11#12")(::Array{Float64,1}, ::Array{Float64,1})
Closest candidates are:
  #11(::Any) at none:2
Stacktrace:
 [1] *(::LinearMaps.FunctionMap{Float64,var"#11#12",Nothing}, ::Array{Float64,1}) at /Users/karrasch/.julia/dev/LinearMaps/src/functionmap.jl:45
 [2] top-level scope at none:0

julia> A.f(zeros(10), rand(10))
ERROR: MethodError: no method matching (::var"#11#12")(::Array{Float64,1}, ::Array{Float64,1})
Closest candidates are:
  #11(::Any) at none:2
Stacktrace:
 [1] top-level scope at none:0
```

**Comment by Jutho** [comment]
My mistake, though it's subtle. There shouldn't be parenthesis around the arguments, otherwise they count as a single argument which is then destructured into two names.
```julia
A = LinearMap(10; issymmetric=true, ismutating=true) do C,B
    C[1] = -2B[1] + B[2]
    for i in 2:length(B)-1
        C[i] = B[i-1] - 2B[i] + B[i+1]
    end
    C[end] = B[end-1] - 2B[end]
    return C
end
```

**Comment by henry2004y** [comment]
I had some other related questions. If I want something more complicated, I need to pass some other arguments for calculating C. For example, some discretized parameters like `dx` and `dy` are needed to solve the 2D poisson equation. How to add input arguments to the construction of LinearMap in these cases?

**Comment by Jutho** [comment]
Why not just create an anonymous function that returns the `LinearMap`, e.g.
```julia
A = (dx,dy) -> LinearMap(10; issymmetric=true, ismutating=true) do C,B
    # something with C, B, dx and dy
end
```
and then use `A(dx,dy)` for some value of `dx` and `dy` in `eigs`, ... or other iterative algorithms

**Comment by henry2004y** [comment]
I have successfully run the 2D poisson solver with the matrix-free form. However, I happened to find that it is much slower than the sparse matrix form. Therefore I tried some simple benchmarks:
```
using SparseArrays, IterativeSolvers, BenchmarkTools, LinearMaps, Test


"""
construct_A_RHS(dx, dy, Nx, Ny, f, un)

Construct the matrix A and the right-hand-side b.
This version is slow because of the low efficient filling of sparse matrix.
"""
function construct_A_RHS(dx, dy, Nx, Ny, f, un)
   N = (Nx-1)*(Ny-1) # total # of unknowns (excluding boundaries)
   A = spzeros(N,N)  # matrix representing the Laplace operator

   # intermediate variables
   diag = -2/dx^2 - 2/dy^2
   invdx2, invdy2 = 1/dx^2, 1/dy^2

   b = vec(f[2:end-1,2:end-1])

   # fill in interior contributions & apply B.C. to RHS
   for iy = 2:Ny, ix = 2:Nx
      i = (iy-2)*(Nx-1) + ix - 1
      iL, iR, iD, iU = i-1, i+1, i-(Nx-1), i+(Nx-1)
      A[i,i] = diag
      if ix > 2
         A[i,iL] = invdx2
      else
         b[i] -= un[1,iy] * invdx2
      end
      if ix < Nx
         A[i,iR] = invdx2
      else
         b[i] -= un[end,iy] * invdx2
      end
      if iy > 2
         A[i,iD] = invdy2
      else
         b[i] -= un[ix,1] * invdy2
      end
      if iy < Ny
         A[i,iU] = invdy2
      else
         b[i] -= un[ix,end] * invdy2
      end
   end

   return A, b
end

"""
construct_RHS(dx, dy, Nx, Ny, f, un)

Construct the right-hand-side b.
"""
function construct_RHS(dx, dy, Nx, Ny, f, un)

   # intermediate variables
   invdx2, invdy2 = 1/dx^2, 1/dy^2

   b = vec(f[2:end-1,2:end-1])

   # apply B.C. to RHS
   for iy = 2:Ny, ix = 2:Nx
      i = (iy-2)*(Nx-1) + ix - 1
      if ix ≤ 2
         b[i] -= un[1,iy] * invdx2
      end
      if ix ≥ Nx
         b[i] -= un[end,iy] * invdx2
      end
      if iy ≤ 2
         b[i] -= un[ix,1] * invdy2
      end
      if iy ≥ Ny
         b[i] -= un[ix,end] * invdy2
      end
   end

   return b
end


nx = 4
ny = 4

x_l = 0.0
x_r = 1.0
y_b = 0.0
y_t = 1.0

dx = (x_r - x_l)/nx
dy = (y_t - y_b)/ny

# allocate array for x and y position of grids, exact solution and source term
x  = Array{Float64}(undef, nx+1)
y  = Array{Float64}(undef, ny+1)
ue = Array{Float64}(undef, nx+1, ny+1)
f  = Array{Float64}(undef, nx+1, ny+1)
un = Array{Float64}(undef, nx+1, ny+1)

for i = 1:nx+1
   x[i] = x_l + dx*(i-1)
end
for i = 1:ny+1
   y[i] = y_b + dy*(i-1)
end

for j = 1:ny+1, i = 1:nx+1
   ue[i,j] = (x[i]^2 - 1.0)*(y[j]^2 - 1.0)

   f[i,j] = -2.0*(2.0 - x[i]^2 - y[j]^2)

   un[i,j] = 0.0
end

# Dirichlet B.C.
un[:,1] = ue[:,1]
un[:,ny+1] = ue[:,ny+1]

un[1,:] = ue[1,:]
un[nx+1,:] = ue[nx+1,:]

r = zeros(Float64, nx+1, ny+1)
init_rms = 0.0
rms = 0.0

# sparse matrix form
A1, b = construct_A_RHS(dx, dy, nx, ny, f, un)


# matrix-free form
diag = -2/dx^2 - 2/dy^2
invdx2, invdy2 = 1/dx^2, 1/dy^2

constructA = (dx, dy, Nx, Ny) -> LinearMap((Nx-1)*(Ny-1); issymmetric=true, ismutating=true) do C,B
   m = Nx - 1

   for i = 1:length(B)
      C[i] = diag * B[i]
   end
   for i = 1:length(B)-1
      if i % m != 0
         C[i] += invdx2 * B[i+1]
         C[i+1] += invdx2 * B[i]
      end
   end
   for i = 1:(length(B)-m)
      C[i] += invdy2 * B[i+m]
      C[i+m] += invdy2 * B[i]
   end
end

b = construct_RHS(dx, dy, nx, ny, f, un)
A2 = constructA(dx, dy, nx, ny)


## Test
@btime U1 = cg(A1, b);
@btime U2 = cg(A2, b); # too much memory usage!!!

U1 = cg(A1, b)
U2 = cg(A2, b)
@test U1 ≈ U2
```

The outputs:
```
  1.349 μs (14 allocations: 1.59 KiB)
  12.296 μs (584 allocations: 10.52 KiB)
Test Passed
```

Why it there so much more memory allocation for the matrix-free form?

**Comment by dkarrasch** [comment]
You should declare the external parameters as constants
```julia
const diag = -2/dx^2 - 2/dy^2
const invdx2, invdy2 = 1/dx^2, 1/dy^2
```
I would highly recommend reading https://docs.julialang.org/en/v1/manual/performance-tips/ for (further) optimizations.

**Comment by henry2004y** [comment]
> You should declare the external parameters as constants
> 
> ```julia
> const diag = -2/dx^2 - 2/dy^2
> const invdx2, invdy2 = 1/dx^2, 1/dy^2
> ```
> 
> I would highly recommend reading https://docs.julialang.org/en/v1/manual/performance-tips/ for (further) optimizations.

Yeah I forgot that these parameters are in global scope. After the fix they are identical.
Thank you folks! It's really a pleasure to walk through these examples!

**Comment by dkarrasch** [comment]
You're welcome. For larger systems, the matrix-free method should be noticeably faster (I quickly benchmarked multiplication with a sparse matrix vs with the function, even more so after applying some micro-optimizations, like avoiding `i % m != 0`, and possibly traversing `C` only once.
