### ISSUE TITLE
Neutral `LinearMap` for Addition?

### ISSUE THREAD

**Issue by Edenhofer** [Jutho/LinearMaps.jl#91]
It would be nice to be able to loop over a set while continuously adding `LinearMap`s to a chain of operators without initializing the reduction variable to a `LinearMap`.

My problem involves adding a lot of `LinearMap`s. The instantiation of the individual summands however is straight forward and can be done in a loop. Hence, I am wondering whether there is an empty set of `LinearMaps.CompositeMap` to which one can start adding maps. This way, I wouldn't need to initialize the reduction variable with a map first just to then loop over the rest.

In code, I am looking for something like this:
```julia
n = 1024

O = LinearMaps.Noop{T}(n)
for s in small_list
    summand::LinearMap = construct_LM_depend_on_s(s)
    O += summand
end
```

**Comment by dkarrasch** [comment]
I'm not sure such a noop-map is necessary. For a quick check, the following already works:
```julia
using LinearMaps
sum([LinearMap(rand(3,3)) for _ in 1:5])
mapreduce(_ -> LinearMap(rand(3,3)), +, 1:5)
```
Rewritten in your terms, this could be
```julia
n = 1024
mapreduce(construct_LM_depend_on_s, +, small_list)
```
if I'm not mistaken. That should certainly work when `small_list` is not empty. For empty `small_list`s, one would need to think again. There is an `init` keyword for `mapreduce`, and the neutral element could be the identity operator `LinearMap(I, n)`?

**Comment by JeffFessler** [comment]
Or maybe simply splatting? :
`+((constructor(s) for s in list)...)`

**Comment by Edenhofer** [comment]
hmm ok, I phrased the question wrongly. Here, `construct_LM_depend_on_s` is just an abbreviation of several lines of code that accesses variables from the outer scope. Hence, outsourcing it into a function would result into a function with a lot of arguments while still being relatively short and overly specific.

**Comment by JeffFessler** [comment]
Your constructor can refer to variables from the outer scope:

```
n = 5
constructor(s) = LinearMap(s*ones(n,n))
A = +((constructor(s) for s in 1:5)...)
```

**Comment by Edenhofer** [comment]
Basically the recommendation would be to put the inner parts of the loop into a function and then use this function in a `mapreduce` or generator expression, right?

While this would work in my case, I would still like to argue in favor of a Noop `LinearMap`. I could easily imagine that if I start pulling more stuff into the map-construction-loop and also perform work unrelated to the construction of the chain of linear maps that I wouldn't be able to collapse it in a reduce call anymore. Though I admit that my simple code example then does not hold anymore.

In essence, my question is about whether a Noop element is of interest.

**Comment by JeffFessler** [comment]
For adding (your focus I think), a Noop would be analogous to `zeros(m,n)`, whereas for multiplying a Noop would perhaps be analogous to `I(n)` for some appropriate `n`.  For `hcat` it would be something different still I think.  Hard to see how to unify all that...

**Comment by Edenhofer** [comment]
The title pretty much sums it up. So yes, I am only focussing on addition. `zeros(m,n)` involves an operation and useless memory allocations.

**Comment by dkarrasch** [comment]
In the version with `mapreduce`, you could also use `do` blocks, which reads nicely:
```julia
mapreduce(+, small_list) do s
    # lots of code
   return # some linear map
end
```
I admit I have a hard time imagining the more complex use case. In fact, since all operations are essentially lazy, you could first construct a concrete collection (in contrast to @JeffFessler's generator approach) of `LinearMap`s, say a tuple, or vector. When you then call `+` or `sum` on it, the extra "allocation" is just for the thin wrapper, so you wouldn't consume any extra memory, basically.

**Comment by Edenhofer** [comment]
My question really is not about the specific use case with my unfortunate code example but more generally about whether a noop operator for addition would be within the scope of this project.

But since we are discussing a lot about code, let's imagine something like this:
```julia
n = 1024

s = 1.
O = LinearMaps.Noop{T}(n)
for s in iterable_list
    # Computation unrelated to creating a summand but dependent on s
    # and potentially sharing intermediate calculation steps with the summand
    s .*= result_of_computation
    # Couple of lines of code that eventually construct a summand of type `LinearMap`
    # ...
    O += summand
end

**Comment by dkarrasch** [comment]
I'm not sure this is good coding style in Julia to begin with. In every loop iteration, the type of `O` is going to change. I'd write this as
```julia
n = 1024 # whatever that is good for :-P
s = 1.0
maps = map(iterable_list) do s # calling this `s` will cover up your external `s` btw
    # do stuff
    return summand
end
O = +(maps...)
```
As I said, having a variable `maps` first and only then `O` doesn't mean you're generating several copies of the same objects. `maps` is going to be a list (vector/tuple) of `LinearMap`s, and in the final `O::LinearCombination` you will have a tuple `O.maps`, where each entry is just a reference to the object referenced in `maps`. You could even construct a tuple right away:
```julia
maps = ntuple(length(iterable_list) do i
    s = iterable list[i]
    # do stuff
    return summand
end
O = +(ntuple...)
```
but I'm not sure there is a big difference, other than that the vector constructed in the first example will likely have an abstract eltype, but `O` should be concretely typed in the end anyway.

I don't want to sound dismissive by any means, but I don't see the need for a neutral additive operator type currently, at least in the context of "initializing" linear combinations.

**Comment by Edenhofer** [comment]
> I'm not sure this is good coding style in Julia to begin with. In every loop iteration, the type of `O` is going to change.

That's exactly why I wrote in the title that it should be an empty `LinearMaps.CompositeMap` so that the type wouldn't change. Therefore it would also need an init value to tell it its shape as otherwise a mismatch in the addition would need to be raised. (That's what the `n` is for.) 

> 
> ```julia
> n = 1024
> ...
> O = +(maps...)
> ```

I edited the code accordingly to fix the syntax issues to make my point clear. IMHO solving the above stated problem with a map is kind of ugly as one would do calculations within the map that are unrelated to the constructing the summand.

> As I said, having a variable `maps` first and only then `O` doesn't mean you're generating several copies of the same objects. `maps` is going to be a list (vector/tuple) of `LinearMap`s, and in the final `O::LinearCombination` you will have a tuple `O.maps`, where each entry is just a reference to the object referenced in `maps`.

That's actually what I did and I don't this solution is particularly bad in any way. I just though that a noop empty `LinearMaps.CompositeMap` might be of general interest.

> I don't want to sound dismissive by any means, but I don't see the need for a neutral additive operator type currently, at least in the context of "initializing" linear combinations.

hmm ok. I kind of have the feeling that I wasn't able to properly bring my argument across as the discussion was a lot about rewriting code snippets but I see that there are a lot of ways to avoid such an operator and that there hence probably isn't a big need for it.

**Comment by dkarrasch** [comment]
> That's exactly why I wrote in the title that it should be an empty `LinearMaps.CompositeMap` so that the type wouldn't change.

The type does change when you add new summands, because the second type parameter corresponds to the tuple of types of the linear maps in the field `maps`. To see it, take a linear map `A`, and then compare the types of `A+A` and `A+A+A`.

> IMHO solving the above stated problem with a map is kind of ugly as one would do calculations within the map that are unrelated to the construction of the summand.

I still don't understand this argument. What's the problem of constructing some kind of container that contains the linear maps that you will want to sum up eventually? Simply collect the `summand`s, and then call `+(maps_list...)` after the loop. The `maps` field is nothing but that, a list of references to the summands (matrices/functions). What are you trying to achieve/avoid by adding them up within the loop (which requires an initialization value)?

**Comment by dkarrasch** [comment]
On a different note: why empty `CompositeMap`? You said you're dealing with `+`, hence `LinearCombination`s. Did you mean an empty `LinearCombination`? Or a `LinearCombination` with one `ZeroMap`?

**Comment by Edenhofer** [comment]
> The type does change when you add new summands, because the second type parameter corresponds to the tuple of types of the linear maps in the field `maps`. To see it, take a linear map `A`, and then compare the types of `A+A` and `A+A+A`.
 
Right, fair point. I forgot about that. Then the proposed loop probably isn't very julia-like if the type continuously changes.

> > IMHO solving the above stated problem with a map is kind of ugly as one would do calculations within the map that are unrelated to the construction of the summand.
> 
> I still don't understand this argument. What's the problem of constructing some kind of container that contains the linear maps that you will want to sum up eventually? Simply collect the `summand`s, and then call `+(maps_list...)` after the loop. The `maps` field is nothing but that, a list of references to the summands (matrices/functions). What are you trying to achieve/avoid by adding them up within the loop (which requires an initialization value)?

I simply though it would be prettier if I wouldn't need to some kind of container regardless of how little overhead it produces.

> On a different note: why empty `CompositeMap`? You said you're dealing with `+`, hence `LinearCombination`s. Did you mean an empty `LinearCombination`? Or a `LinearCombination` with one `ZeroMap`?

Yes, sorry about that! I meant a `LinearCombination` that starts out empty. Since you pointed out that the type would be changing continously, I agree that this is not the proper way to implement it.

Thanks for the comments!
