### ISSUE TITLE
Relation to other libraries

### ISSUE THREAD

**Issue by goretkin** [Jutho/LinearMaps.jl#98]
If it's related, it might be helpful (e.g. for discoverability of this package) to name some possibly related packages in the README.

e.g.
https://github.com/mpf/spot
https://pylops.readthedocs.io/en/latest/

and from https://www.sciencedirect.com/science/article/pii/S2352711019301086

> Conveniently, the Python library SciPy provides a barebone, generic class for the definition and application of linear operators, which we leverage from and build on within the PyLops package as discussed below. Other examples of currently available software packages that provide a general interface to linear operators are the C++ Rice Vector Library[14], the MATLAB Spot and Waveform packages [15,16], the Python fastmat library [17],and the JuliaLinearMaps.jl and JOLI.jl packages [18,19]. Moreover, some open-source software packages that employ a similar construct to solve domain-specific inverse problems are the ASTRA-toolbox[20], Seplib[6,21], Madagascar[22], and Devito[23]. Many of the packages mentioned above however tend to prioritize the ability of solving large inverse problems efficiently in exchange for a loss in the convenient linear-algebra syntax. To the best of our knowledge, only the MATLAB Spot package, and to a lesser degree the Python fastmat library, achieve the best of both worlds.

**Comment by dkarrasch** [comment]
Thanks, @goretkin, for the links. I have added some of the listed packages in our new documentation #102. I have omitted those which have a very specific use case and do function-based linear maps "only" along the way. Feel free suggest further improvements.
