### ISSUE TITLE
Left multiply with Adjoint vector

### ISSUE THREAD

**Issue by JeffFessler** [Jutho/LinearMaps.jl#99]
There is currently a slight inconsistency that arises when left multiplying by a `Transpose` or `Adjoint` vector due to the current design where `y' *A` returns a `LinearMap` because `y'` is treated as a `AbstractArray` rather than as the more specific `Adjoint` vector.  Specifically, the following example shows that there is a slight departure of associativity:
 
```
using LinearMaps: LinearMap
A = LinearMap(ones(3,4))
y = ones(3)
x = ones(4)
y' * (A * x) # scalar
(y' * A) * x # 1-element array
```
Given that 'A*x' returns a vector, I would propose that `y'*A` should return an `Adjoint` vector rather than a `LinearMap` (when `y'` is an `Adjoint` vector).  That (slightly breaking change) would "restore" the associativity.   If `Y'` is an `Adjoint Matrix` then the current behavior seems fine and is consistent with how `A*X` works for a `LinearMap` multiplied by a `Matrix`.  It is only the adjoint vector case that needs refinement.

This issue arose when I was refining the tests for left multiplication for the "multidimensional" versions of
https://github.com/JeffFessler/LinearMapsAA.jl.  Obviously it is not urgent since no one reported it previously, but I would be willing to make a PR if there is agreement that `y'*A` should return an `Adjoint` vector.

Edit: I think it is easy to address for ordinary `*` but I might need help with the `mul!` version.  Or perhaps it is not so important to support `mul!` for this case.

**Comment by Jutho** [comment]
I agree to change!
